# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.2
language: objective-c
# podfile: Demo/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true

cache:
  - bundler
  - cocoapods

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5

# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
before_install:
  - gem install xcpretty -N --no-ri --no-rdoc

script:
- set -o pipefail && xcodebuild clean test -workspace LeeGo.xcworkspace -scheme LeeGo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest' -enableCodeCoverage YES -configuration Debug ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint --allow-warnings
